### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by TitanillaL** [Teaching-projects/SZE-FordProg-2021-web#1]
@hegyhati

**Comment by hegyhati** [comment]
Hm... a dolog kicsit minimalista, de orulok a stack-es megoldasnak a tag-ek ellenorzesere. Monjduk jo lett volna valami szofisztikaltabb dolog, nem csak egy `return 1`. 

Viszont egy csomo mindent lexer retegbol en attennek parser retegbe. 

Most 4/5 kornyeken jarok, ha lenne kis idonk meg, kernem, hogy kicsit pofozd meg. De a zh-id szepen rendben voltak, utolso vizsga(m az egyetemen), masokkal is joszivu voltam, szoval legyen 5. 

Szerk.: most megneztem, tobbieknek mire mit adtam, probalva konzisztenciat tartani. Kozben beugrott az is, hogy ahogy latom, ez most barmit lezar magaval, meg barmibe barmit lehet agyazni, ami hat nem tul idealis. Szoval ne haragudj, inkabb 4 ez. Bocsanat a fentier, kicsit mar faradok.
